apiVersion: composition.krateo.io/v0-0-23
kind: TestWidgetRanges
metadata:
  labels:
    krateo.io/composition-version: v0-0-23
  name: test-widget-ranges
  namespace: demo-system
spec:
  test:
    ok: true
