apiVersion: composition.krateo.io/v0-0-11
kind: TestWidgetRanges
metadata:
  labels:
    krateo.io/composition-version: v0-0-11
  name: test-widget-ranges
  namespace: demo-system
spec:
  test:
    ok: true
