{{- $data := include "demo.items" . | fromJson }}
{{- $items := $data.items }}
{{- range $index, $item := $items }}
---
apiVersion: widgets.templates.krateo.io/v1beta1
kind: Markdown
metadata:
  name: demo-footer-link-{{ $index }}
  namespace: demo-system
spec:
  apiRef:
    name: branches-list
    namespace: demo-system
  widgetData:
    markdown: "Go to branch..."
  widgetDataTemplate:
    - forPath: markdown
      expression: >
        ${ "[\(.getBranches[{{ $index }}] // "N/A")](/git/repo/tree/\(.getBranches[{{ $index }}] // "N/A"))" }
{{- end }}
