apiVersion: widgets.templates.krateo.io/v1beta1
kind: Markdown
metadata:
  name: demo-sidebar-disclaimer
  namespace: demo-system
spec:
  widgetData:
    markdown: >
      **The branch list above take a reconciliation cycle to reflect the actual state.**