{{- $data := include "demo.items" . | fromJson }}
{{- $items := $data.items }}
{{- range $index, $item := $items }}
---
apiVersion: widgets.templates.krateo.io/v1beta1
kind: Panel
metadata:
  name: demo-detail-panel-{{ $index }}
  namespace: demo-system
spec:
  apiRef:
    name: branches-list
    namespace: demo-system
  widgetData:
    title: {{ $item | default "Loading..." }}
    icon: { name: "fa-code-branch" }
    actions: []
    items:
      - resourceRefId: demo-detail-row-{{ $index }}
    footer:
      - resourceRefId: demo-footer-link-{{ $index }}
  widgetDataTemplate:
    - forPath: title
      expression: ${ .getBranches[{{ $index }}] }
  resourcesRefs:
    items:
      - id: demo-detail-row-{{ $index }}
        apiVersion: widgets.templates.krateo.io/v1beta1
        resource: rows
        name: demo-detail-row-{{ $index }}
        namespace: demo-system
        verb: GET
      - id: demo-footer-link-{{ $index }}
        apiVersion: widgets.templates.krateo.io/v1beta1
        resource: markdowns
        name: demo-footer-link-{{ $index }}
        namespace: demo-system
        verb: GET
{{- end }}
