apiVersion: v1
kind: Secret
metadata:
  name: branch-server-endpoint
  namespace: demo-system
stringData:
  # L'URL base del servizio (senza il path /branches)
  server-url: http://branch-server.default.svc.cluster.local