apiVersion: v1
kind: ConfigMap
metadata:
  name: demo-branch-list-oas
  namespace: demo-system
data:
  oas.yaml: |
    openapi: 3.0.3
    info:
      title: Branch Server API
      version: 1.0.0
    servers:
      - url: http://branch-server.default.svc.cluster.local
    paths:
      /branches:
        get:
          summary: List branches
          operationId: branches/list
          responses:
            '200':
              description: A list of branches
              content:
                application/json:
                  schema:
                    type: object
                    properties:
                      branches:
                        type: array
                        items:
                          type: string
