{{- $cm := lookup "v1" "ConfigMap" "demo-system" .Release.Name -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}
  namespace: demo-system
data:
{{- if $cm }}
  {{- toYaml $cm.data | nindent 2 }}
{{- else }}
  items: "[]"
{{- end }}
