apiVersion: widgets.templates.krateo.io/v1beta1
kind: Page
metadata:
  name: demo-pipelines-page
  namespace: demo-system
spec:
  widgetData:
    title: Pipelines Dashboard
    allowedResources: [ rows ]
    items:
      - resourceRefId: demo-main-row
  resourcesRefs:
    items:
      - id: demo-main-row
        apiVersion: widgets.templates.krateo.io/v1beta1
        resource: rows
        name: demo-main-row
        namespace: demo-system
        verb: GET
